### ISSUE TITLE
Add a title on the thead for total Symbol

### ISSUE THREAD

**Issue by Veenoway** [Veenoway/VeenoX#37]
### Is there an existing issue for this?

- [ ] I have looked through the existing issues

### Current Behavior

Actually on the orderbook, there is a title missing for the Total ${symbol}

![Capture d’écran 2024-09-02 à 22 42 06](https://github.com/user-attachments/assets/0a8182b1-e94b-4b9c-9187-1ae94ba03943)

### Expected Behavior

Have a title on the thead `Total ${asset?.symbol}`
There is a function called "formatSymbol" that take 2 params
- Symbol ( PERP_BTC_USDC )
- true ( true if you only want the function to return BTC / false if the function should return BTC-USDC )

### Steps To Reproduce

npm i 
npm run dev 

( node -v 18.17.0 )

**Comment by Uday9316** [comment]
The issue with the dynamic column header for `Total ${symbol}` has been resolved.
![image](https://github.com/user-attachments/assets/cbe00387-39f6-4802-b9cb-54460c10322c)
