### ISSUE TITLE
Orderbook background on mobile devices

### ISSUE THREAD

**Issue by Veenoway** [Veenoway/VeenoX#39]
### Is there an existing issue for this?

- [ ] I have looked through the existing issues

### Current Behavior

Actually on mobile devices the line's orderbook background isn't showing properly on mobile devices.
This issue can only be verified by using your smartphone. Inspector on localhost won't show you the same result as I have on phone ( Iphone )

![363787094-08df2ad8-bf3b-4bc5-83a8-e6169f770712](https://github.com/user-attachments/assets/e19096a3-a7d9-4a0d-98be-394bb8489929)

### Expected Behavior

Background height should fit with the height of the lines like you can see on desktop 

### Steps To Reproduce

This issue is ONLY visible on your phone, you won't be able to test it with the localhost inspector

**Comment by ymcorrea** [comment]
![Untitled](https://github.com/user-attachments/assets/e68cb498-9ee9-4ae0-96c7-3a69b2511f0f)

**Comment by ymcorrea** [comment]
Which branch should I start from?

**Comment by ymcorrea** [comment]
![image](https://github.com/user-attachments/assets/7443c8f7-97a4-4f0e-b832-0473e00b4f11)


Which branch should I start from?
